services:
  - type: web
    name: hotel-management-web-app
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install && npm run prod
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: "" # Not needed; Render uses Apache internally
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false   # Generate locally: php artisan key:generate --show
      - key: APP_URL
        value: https://hotel-management-web-app.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-db-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your-db-name
      - key: DB_USERNAME
        value: your-db-user
      - key: DB_PASSWORD
        sync: false
